#! /bin/bash
DEFAULT_STARGATE_STORAGE="${STARGATE_HOME}/storage"
STARGATE_STORAGE="${STARGATE_STORAGE:-${DEFAULT_STARGATE_STORAGE}}"

DEFAULT_STARGATE_WORK="${STARGATE_HOME}/work"
STARGATE_WORK="${STARGATE_WORK:-${DEFAULT_STARGATE_WORK}}"

DEFAULT_STARGATE_LIBS="${STARGATE_HOME}/libs/*:${STARGATE_HOME}/target/stargate-server-1.0.jar:${STARGATE_HOME}/target/dependency/*"
STARGATE_LIBS="${STARGATE_LIBS:-${DEFAULT_STARGATE_LIBS}}"

DEFAULT_STARGATE_BIN="${STARGATE_HOME}/bin"
STARGATE_BIN="${STARGATE_BIN:-${DEFAULT_STARGATE_BIN}}"

DEFAULT_STARGATE_CONF="${STARGATE_HOME}/config"
STARGATE_CONF="${STARGATE_CONF:-${DEFAULT_STARGATE_CONF}}"

DEFAULT_TMUX_SESSION_NAME="STARGATE_SESSION"
TMUX_SESSION_NAME="${TMUX_SESSION_NAME:-${DEFAULT_TMUX_SESSION_NAME}}"
