#! /bin/bash
DEFAULT_STARGATE_STORAGE="${STARGATE_HOME}/storage"
STARGATE_STORAGE="${STARGATE_STORAGE:-${DEFAULT_STARGATE_STORAGE}}"

DEFAULT_STARGATE_WORK="${STARGATE_HOME}/work"
STARGATE_WORK="${STARGATE_WORK:-${DEFAULT_STARGATE_WORK}}"

DEFAULT_STARGATE_LIBS="${STARGATE_HOME}/libs/*:${STARGATE_HOME}/target/stargate-server-1.0.jar:${STARGATE_HOME}/target/dependency/*"
STARGATE_LIBS="${STARGATE_LIBS:-${DEFAULT_STARGATE_LIBS}}"

DEFAULT_STARGATE_BIN="${STARGATE_HOME}/bin"
STARGATE_BIN="${STARGATE_BIN:-${DEFAULT_STARGATE_BIN}}"

DEFAULT_STARGATE_CONF="${STARGATE_HOME}/config"
STARGATE_CONF="${STARGATE_CONF:-${DEFAULT_STARGATE_CONF}}"

DEFAULT_TMUX_SESSION_NAME="STARGATE_SESSION"
TMUX_SESSION_NAME="${TMUX_SESSION_NAME:-${DEFAULT_TMUX_SESSION_NAME}}"

DEFAULT_STARGATE_LOG="${STARGATE_HOME}/logs"
STARGATE_LOG="${STARGATE_LOG:-${DEFAULT_STARGATE_LOG}}"

DEFAULT_STARGATE_MEMORY_PARAM="-Xms1024m -Xmx3072m -XX:+DisableExplicitGC -XX:+UseG1GC -XX:MaxDirectMemorySize=2G"
STARGATE_MEMORY_PARAM="${STARGATE_MEMORY_PARAM:-${DEFAULT_STARGATE_MEMORY_PARAM}}"
